### ISSUE TITLE
Stráž interface roadmap

### ISSUE THREAD

**Issue by jhpratt** [r-spacex/straz#1]
All of the features listed are in no particular order.

- Basics
  - [ ] Layout (not concerned about mobile for host)
  - [ ] Basic responsiveness for host (screen size >= 1000px)

- Near-parity with Mission Control
  - [ ] Countdown clock via API
  - [ ] Markdown editors - likely going to ditch SimpleMDE in favor of side-by-side editor and preview or GitHub-style tabs
  - [ ] reddit OAuth (with assistance of Stráž API)
  - [ ] Saving section-by-section
  - [ ] Allow updating of webcast link
  - [ ] Allow updating of countdown timer
  - [ ] Tabs on main interface (all, events, sections)
  - [ ] Pre-written events (+ 'emergency' buttons)
  - [ ] Update-by-update saving (how difficult will this be?)
  - [ ] Each update has boolean posted status (use Material-style slider)
  - [ ] Clock icon to insert current countdown time
  - [ ] Recovery of threads
  - [ ] Typing of emojis (preferably *many* more than there already are)

- Post-parity features
  - [ ] Adding/removing sections
  - [ ] Persistence of OAuth between sessions (shouldn't be an issue)
  - [ ] Preload additional data from API (details in r-spacex/mission-control#35, should be trivial)

- End-user layout (thoughts for mobile)
  - [ ] Tabbed layout to avoid clutter
  - [ ] YouTube video full-width at top

- End-user features
  - [ ] Countdown clock updates
  - [ ] Section updates
  - [ ] Event updates
  - [ ] YouTube URL updates
  - [ ] Hold/scrub countdown clock/start
  - [ ] Launch visualization with [Flight Club](https://github.com/r-spacex/FlightClub)

- End-user features (when `is_admin == true` or is host)
  - [ ] "Locking" sections
  - [ ] Integrated Slack panel (in another tab?) _(under consideration)_

The client-server communication should be simplified with the use of Vue, as the data objects will be dynamically bound to inputs. The recovery of threads should also be trivial with the addition of a database, as the post will no longer need parsing.

All admins and the designated host will be able to edit the thread, including all metadata. Each user will be able to request a "lock" on the individual sections, giving them the ability to edit it (with no interference from others). The server is to send out events via websocket notifying who possesses the lock for a given section, ensuring that two users never possess the lock simultaneously.

**Comment by jhpratt** [comment]
Certainly a possibility. Of course, initially it'll be created for r/SpaceX, but if you've been following the corresponding API you'll have noticed I recently abstracted out anything that's specific to that sub.

Ultimately this is going to be a SPA that just has a ton of API calls. Not sure how easy it would be to automatically switch to the SpaceX API when appropriate. There will _likely_ a dropdown menu for launch provider, though now that I think about it, it should be possible to fetch that automatically if we're going off a list of upcoming launches (which LL could provide).

Of course, this will still be fully functional for Roscosmos, ULA, Rocket Lab, etc., but won't fill in some 'extra' details like landing location, nth launch stats, and similar.

This'll certainly be an interesting project, and I actually haven't put a ton of thought into it. More focused on the API currently, which should be just about complete (once reddit OAuth is done).
