### ISSUE TITLE
Stráž roadmap

### ISSUE THREAD

**Issue by jhpratt** [r-spacex/straz#1]
All of the features listed are in no particular order.

- Basics
  - [ ] Layout (*no mobile* for host)
  - [ ] Basic responsiveness (screen size >= 1000px)

- Near-parity with Mission Control
  - [ ] Countdown clock via API
  - [ ] Markdown editors - likely going to ditch SimpleMDE in favor of side-by-side editor and preview or GitHub-style tabs
  - [ ] reddit OAuth
  - [ ] Saving section-by-section
  - [ ] Allow updating of webcast link
  - [ ] Allow updating of countdown timer
  - [ ] Tabs on main interface (all, events, sections)
  - [ ] Pre-written events (+ 'emergency' buttons)
  - [ ] Update-by-update saving (how difficult will this be?)
  - [ ] Each update has boolean posted status (use Material-style slider)
  - [ ] Clock icon to insert current countdown time
  - [ ] Recovery of threads
  - [ ] Typing of emojis (preferably *many* more than there already are)

- Post-parity features
  - [ ] Adding/removing sections
  - [ ] Persistence of OAuth between sessions (shouldn't be an issue with Rails)
  - [ ] Preload additional data from API (details in r-spacex/mission-control#35)

- End-user layout (thoughts for mobile)
  - [ ] Tabbed layout to avoid clutter
  - [ ] YouTube video full-width at top

- End-user features
  - [ ] Countdown clock updates
  - [ ] Section updates
  - [ ] Event updates
  - [ ] YouTube URL updates
  - [ ] Hold/scrub countdown clock/start
  - [ ] Launch visualization with [Flight Club](https://github.com/r-spacex/FlightClub)

The client-server communication should be simplified with the use of Vue, as the data objects will be dynamically bound to inputs. The recovery of threads should also be trivial with the addition of a database, as the post will no longer need parsing.

**Comment by jhpratt** [comment]
Basic REST API with no security checks (besides not modifying ID on `update`) has been completed. All events are emitted into relevant namespaces via Socket.io.

Endpoint return value of `update` and `delete` will almost certainly change to the object that was just modified/deleted. The returns for `create` and `read` should be considered frozen, as they both already return the object.

I'll add in a markdown file for the endpoints and their return values, as well as their (future) prerequisites. This will either be done tomorrow or Wednesday, depending on how much time I have.
